# SPDX-FileCopyrightText: 2026 Copyright (c) Contributors to the Eclipse Foundation
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [
  ".bazelversion",
  "Cargo.lock",
  "LICENSE",
  "MODULE.bazel.lock",
  "mbedtls-sys/src/bindings.rs",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Copyright (c) Contributors to the Eclipse Foundation"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/mbedtls-4.0.0/**"
precedence = "override"
SPDX-FileCopyrightText = "Copyright The Mbed TLS Contributors"
SPDX-License-Identifier = "Apache-2.0"
