/*
 * SPDX-FileCopyrightText: 2026 Copyright (c) Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 */

//! Raw FFI bindings to mbedtls 4.0.0, generated by bindgen.
//!
//! These are not intended for direct use. Use `mbedtls-rs` instead.
//!
//! The bindings are pre-generated and checked in as `src/bindings.rs`.
//! To regenerate after updating vendor/mbedtls-4.0.0/, run:
//!
//! ```sh
//! scripts/regenerate-bindings.sh
//! ```
//!
//! This requires clang to be installed.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]

include!("bindings.rs");

#[cfg(all(feature = "multithread", windows))]
unsafe extern "C" {
    /// Windows threading shim (csrc/threading_win32.c).
    ///
    /// Registers SRWLOCK/CONDITION_VARIABLE based callbacks via
    /// `mbedtls_threading_set_alt`. Must be called once, before any other
    /// mbedtls function, when the `multithread` feature is enabled on Windows.
    pub fn mbedtls_rs_threading_setup();
}
